# Generated by Django 3.2.12 on 2022-03-05 19:52

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=posts.models.post_image_upload_handler),
        ),
    ]
