# Generated by Django 3.2.6 on 2021-09-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 40 characters or fewer.', max_length=40, unique=True, verbose_name='username')),
                ('profile_picture', models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures')),
                ('profile_background', models.ImageField(default='profile_backgrounds/default.png', upload_to='profile_backgrounds')),
                ('bio', models.TextField(blank=True, help_text='Write something about yourself!', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
