# Generated by Django 3.2.12 on 2022-03-05 19:52

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(default='profile_backgrounds/default.png', upload_to=profiles.models.profile_images_handler),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to=profiles.models.profile_images_handler),
        ),
    ]
