# Generated by Django 3.2.12 on 2022-03-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220309_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followers',
        ),
    ]
