version: '3.8'

services:
  django:
    build: ./
    command: gunicorn socially.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./socially/.env
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
