name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: passw0rd123!#@
          POSTGRES_DB: ghactions
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        ALLOWED_HOSTS: 127.0.0.1
        DEBUG: False
        SECRET_KEY: si)gsc2)1wc88djangotestkeyoudw#jq$ouqvf+s1dhm3^454
        DB_NAME: ghactions
        DB_HOST: 127.0.0.1
        DB_USERNAME: postgres
        PORT: 5432
        DB_PASSWORD: passw0rd123!#@
      run: |
        pytest profiles posts accounts